version: 2

builds:
  - main: ./cmd/srs
    binary: srs
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/jvcorredor/srs-tui/internal/version.Version={{ .Version }}
      - -X github.com/jvcorredor/srs-tui/internal/version.Commit={{ .Commit }}
      - -X github.com/jvcorredor/srs-tui/internal/version.Date={{ .Date }}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: ["tar.gz"]
    name_template: >-
      srs_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: checksums.txt
  algorithm: sha256

release:
  prerelease: auto

changelog:
  disable: true

snapshot:
  version_template: "{{ incpatch .Version }}-snapshot"
